# -*- coding: utf-8 -*-
"""Projet_AI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nC9T2hT6NQZ3Golm1YnrkL05PgC5BTlC

# **Description du Dataset Telco Customer Churn**

## Sujet du projet
Ce dataset concerne la **prédiction du churn client** (départ) d'une entreprise de télécommunications fictive en Californie. L'objectif est de prédire quels clients vont quitter l'entreprise (classification binaire : Oui/Non) en analysant leurs caractéristiques démographiques, services souscrits et données financières.

## Caractéristiques principales
- **Taille** : 7 043 clients (lignes) × 21 colonnes (features + target)
- **Type** : Classification supervisée binaire (Churn : Yes/No)
- **Source** : Kaggle (https://www.kaggle.com/datasets/blastchar/telco-customer-churn)
- **Taux de churn** : ~26,5% des clients partent
"""

# Import des librairies
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Chargement du dataset
df = pd.read_csv("Telco_Customer_Churn.csv")

# Aperçu général
print("=== INFORMATIONS GÉNÉRALES ===")
print(f"Taille du dataset : {df.shape}")
print(f"Nombre de clients : {df.shape[0]:,}")
print(f"Nombre de features : {df.shape[1]-1} (+ 1 target)")
print("\n" + "="*50)

"""## **Types des données et structure**
Le dataset contient principalement :
- **Variables numériques** : tenure (durée), MonthlyCharges, TotalCharges
- **Variables catégorielles** : sexe, services souscrits, type de contrat, méthode de paiement
- **Target** : Churn (Yes/No)

"""

print("=== TYPES DE DONNÉES ===")
print(df.dtypes)
print("\n=== INFORMATIONS COMPLÈTES ===")
print(df.info())
print("\n=== PREMIÈRES LIGNES ===")
df.head()

# Visualisation rapide de la target
plt.figure(figsize=(10,4))

plt.subplot(1,2,1)
df['Churn'].value_counts().plot(kind='bar', color=['skyblue','pink'])
plt.title('Distribution du Churn')
plt.ylabel('Nombre de clients')
plt.xticks(rotation=0)

plt.subplot(1,2,2)
plt.pie(df['Churn'].value_counts(), labels=['Non','Oui'], autopct='%1.1f%%')
plt.title('Répartition Churn (%)')

plt.tight_layout()
plt.show()

print("Taux de churn :", round((df['Churn']=='Yes').mean()*100,1), "%")

"""**Analyse exploratoire initiale**"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

print("=== DIAGNOSTIC INITIAL ===\n")

# 1. Vérification des valeurs manquantes
print("📊 Valeurs manquantes par colonne :")
missing = df.isnull().sum()
if missing.sum() == 0:
    print("  ✓ Aucune valeur manquante détectée")
else:
    print(missing[missing > 0])

# 2. Vérification des types de données
print("\n📋 Types de données :")
print(df.dtypes.value_counts())

# 3. Vérification spécifique de TotalCharges
print(f"\n🔍 TotalCharges - Type actuel : {df['TotalCharges'].dtype}")
if df['TotalCharges'].dtype == 'object':

    # Détecter les valeurs non numériques
    non_numeric = pd.to_numeric(df['TotalCharges'], errors='coerce').isnull().sum()
    print(f"  Valeurs non-numériques détectées : {non_numeric}")

print(f"\n📐 Shape du dataset : {df.shape}")
print(f"🎯 Distribution de Churn : \n{df['Churn'].value_counts(normalize=True)}")

"""**Nettoyage et préparation des données (AVANT le split)**"""

print("=== NETTOYAGE DES DONNÉES ===\n")

# 1. Correction de TotalCharges
print("🔧 Correction de TotalCharges...")
print(f"  Avant : dtype = {df['TotalCharges'].dtype}")

# Convertir en numérique (les chaînes vides deviennent NaN)
df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')

# Compter les NaN créés
nan_count = df['TotalCharges'].isnull().sum()
print(f"  NaN créés : {nan_count}")

# ✅ ANALYSE QUANTITATIVE pour JUSTIFIER l'imputation
print("  📊 Analyse des NaN :")
tenure_zero_nan = df[(df['tenure'] == 0) & (df['TotalCharges'].isnull())].shape[0]
tenure_zero_total = (df['tenure'] == 0).sum()
print(f"    - Clients tenure=0 avec NaN TotalCharges : {tenure_zero_nan}")
print(f"    - Total clients tenure=0 : {tenure_zero_total}")
print(f"    → {100*tenure_zero_nan/tenure_zero_total:.1f}% des nouveaux clients ont NaN")

# Appliquer l'imputation
df['TotalCharges'] = df['TotalCharges'].fillna(0)

print(f"  Après : dtype = {df['TotalCharges'].dtype}, NaN = {df['TotalCharges'].isnull().sum()}")
print("  ✓ Correction terminée\n")

# 2. Vérification de la cohérence des données
print("🔍 Vérification de cohérence :")
print(f"  tenure = 0 : {(df['tenure'] == 0).sum()} clients")
print(f"  TotalCharges = 0 : {(df['TotalCharges'] == 0).sum()} clients")

# ✅ VÉRIFICATION ADDITIONNELLE : cohérence métier
coherent_new_clients = df[(df['tenure'] == 0) & (df['TotalCharges'] == 0)].shape[0]
print(f"  ✅ Nouveaux clients cohérents (tenure=0 ET TotalCharges=0) : {coherent_new_clients}")
print(f"     → {100*coherent_new_clients/tenure_zero_total:.1f}% de cohérence parfaite\n")

"""**Analyse des outliers**"""

print("=== ANALYSE DES OUTLIERS ===\n")

# Colonnes numériques à analyser
num_cols = ['tenure', 'MonthlyCharges', 'TotalCharges']

print("📊 Détection outliers (méthode IQR 1.5) :\n")
for col in num_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    outliers = ((df[col] < lower_bound) | (df[col] > upper_bound)).sum()
    outliers_pct = (outliers / len(df)) * 100

    print(f"🔍 {col}:")
    print(f"   Min={df[col].min():.2f}, Max={df[col].max():.2f}")
    print(f"   Q1={Q1:.2f}, Q3={Q3:.2f}, IQR={IQR:.2f}")
    print(f"   📈 Outliers : {outliers} ({outliers_pct:.1f}%)")
    print(f"   Seuil : [{lower_bound:.2f}, {upper_bound:.2f}]")
    print()

# 🎯 JUSTIFICATION DÉTAILLÉE + DÉCISION
print("🎯 ANALYSE MÉTIER DES OUTLIERS :")
print("• MonthlyCharges > 118$ = clients VIP (Fibre+Streaming+Phone)")
print("• TotalCharges élevés = clients fidèles longue durée")
print("• tenure=72mois = clients premium légitimes")
print()
print("🚫 RISQUES SUPPRESSION :")
print("• Perte clients VIP (26% churn potentiel)")
print("• Biais métier : sous-représentation clients premium")
print()
print("✅ SOLUTION TECHNIQUE : RobustScaler")
print("   • Basé médiane/IQR → résistant outliers")
print("   • Normalise SANS supprimer données business")
print("   • StandardScaler (moyenne/écart-type) serait biaisé")
print()
print("🎉 Décision : CONSERVATION outliers + RobustScaler\n")

""" **Split Train/Test**"""

print("=== SPLIT TRAIN/TEST ===\n")


X = df.drop(['Churn', 'customerID'], axis=1)  # customerID supprimé !
y = df['Churn'].map({'Yes': 1, 'No': 0})

print("📊 Vérification avant split :")
print(f"   Features utilisées : {X.shape[1]} (customerID exclu)")
print(f"   Distribution globale Churn :\n{y.value_counts(normalize=True).round(3)}")

# ✅ Split 80/20 avec stratify
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=123, stratify=y
)

print(f"\n✅ SPLIT RÉUSSI :")
print(f"   Train : {X_train.shape[0]} échantillons ({X_train.shape[0]/len(X)*100:.1f}%)")
print(f"   Test  : {X_test.shape[0]} échantillons ({X_test.shape[0]/len(X)*100:.1f}%)")
print(f"\n🎯 Distribution Churn :")
print(f"   Train :\n{y_train.value_counts(normalize=True).round(3)}")
print(f"   Test  :\n{y_test.value_counts(normalize=True).round(3)}")

# ✅ VÉRIFICATION ÉQUILIBRE (différence < 1%)
train_churn = y_train.mean()
test_churn = y_test.mean()
print(f"\n🔍 Équilibre Churn : train={train_churn:.3f}, test={test_churn:.3f}")
print(f"   Différence : {abs(train_churn-test_churn)*100:.2f}% ✅")
print("\n🎉 Split parfait - Prêt pour le preprocessing !")

"""##  Construction du Pipeline de Prétraitement

**Variables utilisées :**
- **Numériques (3)** : `tenure`, `MonthlyCharges`, `TotalCharges`
- **Catégorielles (17)** : toutes les autres colonnes

### **Justification des choix :**

**1. RobustScaler (numérique)**  
 Résistant aux outliers (médiane + IQR)  
 Préférable à StandardScaler pour `MonthlyCharges`/`TotalCharges`

**2. OneHotEncoder (catégoriel)**  
- `drop='first'` →  Multicolinéarité évitée  
- `handle_unknown='ignore'` →  Production safe  
- `sparse_output=False` →  Compatibilité modèles  

** Pas de Data Leakage :**  
`fit()` → **UNIQUEMENT train**  
`transform()` → train + test séparément

---

##  **PROBLÈME : 5663 features !**
**5634 clients < 5663 features = OVERFITTING garanti**

** SOLUTION : SelectKBest(f_classif, k=30)**  
 Réduit 5663 → 30 meilleures features  
 Évite overfitting  
 Garde les features prédictives du churn

"""

from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import RobustScaler, OneHotEncoder
from sklearn.feature_selection import SelectKBest, f_classif

print("=== PIPELINE COMPLET + SÉLECTION FEATURES ===\n")

# ✅ Identification colonnes (customerID déjà exclu)
num_cols = ['tenure', 'MonthlyCharges', 'TotalCharges']
cat_cols = [col for col in X_train.columns if col not in num_cols]

print(f"📊 Colonnes détectées :")
print(f"   Numériques : {len(num_cols)} → {num_cols}")
print(f"   Catégorielles : {len(cat_cols)} → {cat_cols[:3]}...")

# Pipeline numérique (RobustScaler → outliers)
numeric_pipeline = Pipeline([
    ('scaler', RobustScaler())
])

# Pipeline catégoriel (OneHotEncoder optimisé)
categorical_pipeline = Pipeline([
    ('onehot', OneHotEncoder(
        drop='first',           # ❌ Multicolinéarité
        handle_unknown='ignore', # ✅ Production safe
        sparse_output=False      # ✅ Dense array
    ))
])

#  Pipeline complet
preprocessor = ColumnTransformer([
    ('num', numeric_pipeline, num_cols),
    ('cat', categorical_pipeline, cat_cols)
], verbose_feature_names_out=False)

#  FIT UNIQUEMENT SUR TRAIN (pas de data leakage !)
print("\n🔄 Étape 1 : Fit preprocessing sur TRAIN...")
preprocessor.fit(X_train)

# Transform train ET test
X_train_proc = preprocessor.transform(X_train)
X_test_proc = preprocessor.transform(X_test)

# 📈 ANALYSE DIMENSIONNELLE - AVANT sélection
feature_names = preprocessor.get_feature_names_out()
print(f"\n🚨 DIMENSIONNALITÉ APRÈS PREPROCESSING :")
print(f"   Avant : {X_train.shape[1]} features")
print(f"   APRÈS OHE : {X_train_proc.shape[1]} features")
print(f"   💥 Explosion : {X_train_proc.shape[1]/X_train.shape[1]:.0f}x !")

# ✅ ÉTAPE 2 : SÉLECTION DES 30 MEILLEURES FEATURES
print("\n🔄 Étape 2 : SelectKBest(k=30) sur TRAIN...")
selector = SelectKBest(score_func=f_classif, k=30)
X_train_selected = selector.fit_transform(X_train_proc, y_train)
X_test_selected = selector.transform(X_test_proc)

# Noms des features sélectionnées
selected_idx = selector.get_support(indices=True)
selected_features = feature_names[selected_idx]

print(f"\n🎯 DIMENSIONNALITÉ FINALE :")
print(f"   Train : {X_train_selected.shape}")
print(f"   Test  : {X_test_selected.shape}")
print(f"   ➡️ Réduction : {X_train_proc.shape[1]} → {X_train_selected.shape[1]} (-{100*(1-X_train_selected.shape[1]/X_train_proc.shape[1]):.1f}%)")

print(f"\n🏆 TOP 5 FEATURES SÉLECTIONNÉES :")
print(f"   {selected_features[:5].tolist()}")

print(f"\n✅ PIPELINE COMPLET PRÊT POUR LES MODÈLES !")

"""##  Initialisation des 7 Modèles ML**

### ** Objectifs de cette étape**
- Configurer **7 modèles** différents avec paramètres adaptés au churn
- Appliquer **`class_weight='balanced'`** pour gérer le déséquilibre (73% No / 27% Yes)
- Préparer pour **validation croisée 5-fold** (comme dans le TD)

### ** Modèles sélectionnés**
1. **Logistic Regression** : Linéaire, interprétable
2. **Random Forest** : Ensemble d'arbres, robuste
3. **KNN** : Voisins proches
4. **Naive Bayes** : Probabiliste rapide
5. **Decision Tree** : Arbre simple
6. **XGBoost** : Boosting performant
7. **SVC** : Support Vector Classifier

**Initialisation des modèles**
"""

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from xgboost import XGBClassifier

print("🚀 INITIALISATION DES 7 MODÈLES \n")

models = {
    'Logistic Regression': LogisticRegression(
        max_iter=2000, random_state=42, class_weight='balanced'
    ),
    'Random Forest': RandomForestClassifier(
        n_estimators=100, random_state=42, class_weight='balanced'
    ),
    'SVC': SVC(
        random_state=42, class_weight='balanced', probability=True
    ),
    'KNN': KNeighborsClassifier(n_neighbors=5),
    'Naive Bayes': GaussianNB(),
    'Decision Tree': DecisionTreeClassifier(
        max_depth=10, random_state=42, class_weight='balanced'
    ),
    'XGBoost': XGBClassifier(
        random_state=42, eval_metric='logloss', n_estimators=100
    )
}

print("📋 MODÈLES PRÊTS POUR VALIDATION CROISÉE :")
for i, name in enumerate(models.keys(), 1):
    print(f"   {i}. ✅ {name}")

print(f"\n📊 Total : {len(models)} modèles")
print(f"🎯 Données : X_train_selected ({X_train_selected.shape})")
print(f"🎯 Labels  : y_train ({y_train.shape})")

"""**Validation croisée 5-fold**"""

from sklearn.model_selection import cross_validate, cross_val_score
from sklearn.metrics import get_scorer_names

print("🔄 VALIDATION CROISÉE 5-FOLD SUR X_train_selected UNIQUEMENT\n")

#  Métriques classification
scoring = ['accuracy', 'f1', 'precision', 'recall', 'roc_auc']

print("📈 Métriques évaluées :")
for metric in scoring:
    print(f"   • {metric}")

print(f"\n🔍 5-FOLD CV sur {X_train_selected.shape[0]} échantillons...\n")

#  Résultats pour CHAQUE modèle
results = {}
for name, model in models.items():
    print(f"[{name}] Validation croisée...")

    #  cross_validate = plusieurs métriques
    cv_results = cross_validate(
        model, X_train_selected, y_train,
        cv=5,
        scoring=scoring,
        return_train_score=False  # Seulement test scores
    )

    # Moyennes + écarts-types
    f1_mean = cv_results['test_f1'].mean()
    f1_std = cv_results['test_f1'].std()

    results[name] = {
        'f1_mean': f1_mean,
        'f1_std': f1_std,
        'accuracy_mean': cv_results['test_accuracy'].mean()
    }

    print(f"   F1-score : {f1_mean:.3f} (±{f1_std:.3f})")
    print()

#  Classement par F1-score
print("🏆 CLASSEMENT F1-SCORE (moyen ± écart-type) :")
ranking = sorted(results.items(), key=lambda x: x[1]['f1_mean'], reverse=True)

for i, (name, res) in enumerate(ranking, 1):
    print(f"   {i}. {name:18} {res['f1_mean']:.3f} ±{res['f1_std']:.3f}")

best_model_name = ranking[0][0]
print(f"\n🎯 MEILLEUR MODÈLE : {best_model_name}")

"""Pourquoi AUC-ROC + F1 ?

 F1 : Dépend du seuil fixe 0.5 (50% churn probabilité)

 AUC-ROC : Teste TOUS les seuils, parfait pour churn déséquilibré (73% No / 27% Yes)

##  Évaluation sur le test set
"""

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

print("🏁 ÉVALUATION FINALE SUR LE TEST SET \n")

results_test = {}
best_model = None
best_model_name = None
best_f1 = 0


for name, model in models.items():
    print(f"[{name}] Entraînement final sur TOUT X_train_selected...")

    # Entraînement sur tout le train set
    model.fit(X_train_selected, y_train)

    # Prédiction sur le test set
    y_pred = model.predict(X_test_selected)

    # Calcul des métriques
    results_test[name] = {
        'Accuracy': accuracy_score(y_test, y_pred),
        'Precision': precision_score(y_test, y_pred, zero_division=0),
        'Recall': recall_score(y_test, y_pred, zero_division=0),
        'F1-Score': f1_score(y_test, y_pred, zero_division=0)
    }

    # Affichage
    print(f"  Accuracy  : {results_test[name]['Accuracy']:.3f}")
    print(f"  Precision : {results_test[name]['Precision']:.3f}")
    print(f"  Recall    : {results_test[name]['Recall']:.3f}")
    print(f"  F1-Score  : {results_test[name]['F1-Score']:.3f}")
    print("-" * 50)

    # Identifier le meilleur modèle (F1-Score)
    if results_test[name]['F1-Score'] > best_f1:
        best_f1 = results_test[name]['F1-Score']
        best_model = model
        best_model_name = name

# 🏆 Résumé final
print(f"\n🏆 MEILLEUR MODÈLE FINAL : {best_model_name}")
print(f"   F1-Score test = {best_f1:.3f}")
print(f"   Données utilisées : {X_test_selected.shape}")

import matplotlib.pyplot as plt
import numpy as np

metrics = ['F1-Score', 'Accuracy', 'Precision', 'Recall']
model_names = list(results_test.keys())

# Préparer les données
data = np.array([[results_test[model][metric] for metric in metrics] for model in model_names])

fig, ax = plt.subplots(figsize=(12,6))
x = np.arange(len(model_names))
width = 0.2

# Tracer les barres pour chaque métrique
for i, metric in enumerate(metrics):
    ax.bar(x + i*width, data[:, i], width=width, label=metric)

ax.set_xticks(x + width * (len(metrics)-1) / 2)
ax.set_xticklabels(model_names, rotation=45, ha='right', fontsize=10)
ax.set_ylabel('Score')
ax.set_title('Comparaison des Modèles sur Test Set')
ax.legend()

plt.tight_layout()
plt.show()

from sklearn.metrics import classification_report, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns

print(f"📈 RAPPORT DÉTAILLÉ : {best_model_name.upper()}\n")
print("="*60)

# Prédictions du meilleur modèle
y_pred_best = best_model.predict(X_test_proc)

# Rapport de classification
print("\n📋 Classification Report :\n")
print(classification_report(y_test, y_pred_best,
                          target_names=['No Churn (0)', 'Churn (1)'],
                          digits=3))

# Matrice de confusion
cm = confusion_matrix(y_test, y_pred_best)

fig, ax = plt.subplots(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=['No Churn', 'Churn'],
            yticklabels=['No Churn', 'Churn'],
            cbar_kws={'label': 'Count'})

plt.title(f'Matrice de Confusion - {best_model_name}\nF1-Score = {best_f1:.3f}',
          fontsize=14, fontweight='bold')
plt.ylabel('Valeur Réelle', fontsize=12)
plt.xlabel('Valeur Prédite', fontsize=12)
plt.tight_layout()
plt.show()

# Interprétation de la matrice
print(f"\n📊 Interprétation de la matrice de confusion :")
print(f"  Vrais Négatifs (TN)  : {cm[0,0]} - Clients correctement prédits comme non-churn")
print(f"  Faux Positifs (FP)   : {cm[0,1]} - Clients non-churn prédits comme churn")
print(f"  Faux Négatifs (FN)   : {cm[1,0]} - Clients churn prédits comme non-churn")
print(f"  Vrais Positifs (TP)  : {cm[1,1]} - Clients correctement prédits comme churn")

import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from matplotlib.patches import FancyBboxPatch
import numpy as np

# Créer une infographie professionnelle
fig = plt.figure(figsize=(12, 8))
fig.patch.set_facecolor('#0A0E27')  # Fond bleu foncé professionnel

# Titre principal
fig.text(0.5, 0.95, ' Prédiction du Churn Client - Telco Dataset',
         ha='center', fontsize=24, fontweight='bold', color='white')
fig.text(0.5, 0.91, 'Machine Learning Project | 6 Modèles Comparés | 7043 Clients Analysés',
         ha='center', fontsize=11, color='#64B5F6', style='italic')

# Section 1 : Métriques clés (gauche)
ax1 = fig.add_axes([0.05, 0.55, 0.28, 0.30])
ax1.axis('off')
metrics_box = FancyBboxPatch((0.05, 0.1), 0.9, 0.8,
                             boxstyle="round,pad=0.05",
                             facecolor='#1E3A5F', edgecolor='#64B5F6', linewidth=2)
ax1.add_patch(metrics_box)
ax1.text(0.5, 0.75, ' RÉSULTATS', ha='center', fontsize=16,
         fontweight='bold', color='white')
ax1.text(0.5, 0.55, 'F1-Score : 0.615', ha='center', fontsize=13, color='#4CAF50')
ax1.text(0.5, 0.40, 'ROC-AUC : 0.78', ha='center', fontsize=13, color='#FFC107')
ax1.text(0.5, 0.25, 'Accuracy : 82%', ha='center', fontsize=13, color='#2196F3')

# Section 2 : Comparaison modèles (centre)
ax2 = fig.add_axes([0.37, 0.55, 0.28, 0.30])
models = ['Logistic\nRegression', 'Random\nForest', 'XGBoost',
          'KNN', 'Decision\nTree', 'Naive\nBayes']
f1_scores = [0.615, 0.562, 0.553, 0.533, 0.544, 0.420]
colors = ['#4CAF50'] + ['#64B5F6']*5
bars = ax2.barh(models, f1_scores, color=colors, edgecolor='white', linewidth=1.5)
ax2.set_xlim(0, 0.7)
ax2.set_xlabel('F1-Score', fontsize=10, color='white')
ax2.set_title(' Comparaison des Modèles', fontsize=13,
              fontweight='bold', color='white', pad=10)
ax2.tick_params(colors='white', labelsize=9)
ax2.set_facecolor('#1E3A5F')
for spine in ax2.spines.values():
    spine.set_edgecolor('#64B5F6')
    spine.set_linewidth(2)
# Ajouter valeurs sur barres
for i, (bar, score) in enumerate(zip(bars, f1_scores)):
    ax2.text(score + 0.01, i, f'{score:.3f}',
             va='center', fontsize=9, color='white', fontweight='bold')

# Section 3 : Pipeline technique (droite)
ax3 = fig.add_axes([0.69, 0.55, 0.28, 0.30])
ax3.axis('off')
pipeline_box = FancyBboxPatch((0.05, 0.1), 0.9, 0.8,
                              boxstyle="round,pad=0.05",
                              facecolor='#1E3A5F', edgecolor='#64B5F6', linewidth=2)
ax3.add_patch(pipeline_box)
ax3.text(0.5, 0.75, ' PIPELINE ML', ha='center', fontsize=14,
         fontweight='bold', color='white')
pipeline_steps = [
    '1. Nettoyage données',
    '2. Encodage OneHot',
    '3. Normalisation (RobustScaler)',
    '4. Sélection features (50)',
    '5. Optimisation GridSearchCV'
]
for i, step in enumerate(pipeline_steps):
    ax3.text(0.15, 0.60 - i*0.10, f'✓ {step}',
             fontsize=9, color='#64B5F6', va='top')

# Section 4 : Matrice de confusion (bas gauche)
ax4 = fig.add_axes([0.08, 0.15, 0.25, 0.25])
conf_matrix = np.array([[927, 108], [176, 198]])
im = ax4.imshow(conf_matrix, cmap='Blues', alpha=0.8)
ax4.set_xticks([0, 1])
ax4.set_yticks([0, 1])
ax4.set_xticklabels(['No Churn', 'Churn'], fontsize=10, color='white')
ax4.set_yticklabels(['No Churn', 'Churn'], fontsize=10, color='white')
ax4.set_xlabel('Prédiction', fontsize=10, color='white', fontweight='bold')
ax4.set_ylabel('Réalité', fontsize=10, color='white', fontweight='bold')
ax4.set_title('Matrice de Confusion', fontsize=12, color='white', fontweight='bold', pad=10)
for i in range(2):
    for j in range(2):
        text_color = 'white' if conf_matrix[i, j] > 400 else 'black'
        ax4.text(j, i, f'{conf_matrix[i, j]}',
                ha="center", va="center", fontsize=14,
                color=text_color, fontweight='bold')

# Section 5 : Technologies (bas centre)
ax5 = fig.add_axes([0.38, 0.15, 0.24, 0.25])
ax5.axis('off')
tech_box = FancyBboxPatch((0.05, 0.05), 0.9, 0.9,
                          boxstyle="round,pad=0.05",
                          facecolor='#1E3A5F', edgecolor='#64B5F6', linewidth=2)
ax5.add_patch(tech_box)
ax5.text(0.5, 0.80, ' TECHNOLOGIES', ha='center', fontsize=13,
         fontweight='bold', color='white')
techs = ['Python 3.8+', 'scikit-learn', 'XGBoost',
         'Pandas', 'Matplotlib', 'Jupyter']
for i, tech in enumerate(techs):
    row = i // 2
    col = i % 2
    x = 0.25 if col == 0 else 0.65
    y = 0.60 - row * 0.15
    ax5.text(x, y, f'• {tech}', fontsize=9, color='#64B5F6')

# Section 6 : Impact business (bas droite)
ax6 = fig.add_axes([0.68, 0.15, 0.28, 0.25])
ax6.axis('off')
impact_box = FancyBboxPatch((0.05, 0.05), 0.9, 0.9,
                            boxstyle="round,pad=0.05",
                            facecolor='#1E3A5F', edgecolor='#4CAF50', linewidth=2)
ax6.add_patch(impact_box)
ax6.text(0.5, 0.75, ' IMPACT BUSINESS', ha='center', fontsize=13,
         fontweight='bold', color='white')
impacts = [
    '↓ 42% Fausses alarmes',
    '↑ 53% Détection churns',
    ' ROI estimé : +25%',
    ' Temps analyse : -60%'
]
for i, impact in enumerate(impacts):
    ax6.text(0.15, 0.55 - i*0.12, impact, fontsize=9,
             color='#4CAF50', fontweight='bold')

# Footer
fig.text(0.5, 0.04, ' Fatma Hajjeji  | GitHub: www.linkedin.com/in/fatma-hajjeji-29b1a8295',
         ha='center', fontsize=10, color='#64B5F6', style='italic')
fig.text(0.5, 0.01, ' fatmahajjeji9@gmail.com |  linkedin.com/in/fatma-hajjeji-29b1a8295l',
         ha='center', fontsize=9, color='#888888')

plt.savefig('linkedin_project_showcase.png', dpi=300, bbox_inches='tight',
            facecolor='#0A0E27', edgecolor='none')
plt.show()

print(" Image créée : linkedin_project_showcase.png")
print("📏 Format : 1200x800px (optimal LinkedIn)")